use sh instead of bash moved sh options to a separate set call do not fail 'which' calls added funtion find_free_servernum to find first free server number instead of picking a random server number added function wait_for_x to wait the start of X server and timeout after 10S instead of a static sleep Fixed -s option Added bin/autopilot-sandbox-run to setup.py

diff --git a/bin/autopilot-sandbox-run b/bin/autopilot-sandbox-run
--- a/bin/autopilot-sandbox-run
+++ b/bin/autopilot-sandbox-run
@@ -1,4 +1,4 @@
-#!/bin/bash -eu
+#!/bin/sh
 
 #
 # Runner to execute autopilot locally
@@ -22,27 +22,29 @@
 # You should have received a copy of the GNU General Public License along with
 # this program; if not, write to the Free Software Foundation, Inc.,
 # 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA
+set -eu
 
 # General Settings
 RC=0  # Main return code
 BINDIR=$(dirname $(readlink -f $0))
 XEPHYR=0
-XEPHYR_CMD="$(which Xephyr)"
+XEPHYR_CMD="$(which Xephyr||true)"
 XEPHYR_OPT="-ac -br -noreset"
 
-XVFB_CMD="$(which Xvfb)"
+XVFB_CMD="$(which Xvfb||true)"
 XVFB_OPT=""
 
 AP_CMD="$(which autopilot)"
 AP_OPT=""
 
-SERVERNUM=$(shuf -n1 -i5-99)
+SERVERNUM=5
 SCREEN="1024x768x24"
 
 DBUS_SESSION_BUS_PID=""
 X_PID=""
 
 usage() {
+    # Display usage and exit with error
     cat<<EOF
 Usage: $(basename $0) [OPTIONS...] TEST [TEST...]
 Runs autopilot tests in a 'fake' Xserver with Xvfb or Xephyr. autopilot runs
@@ -61,6 +63,48 @@ Options:
 EOF
     RC=1
     exit
+}
+
+find_free_servernum() {
+    # Find a free server number by looking at .X*-lock files in /tmp.
+    # Inspired from xvfb-run
+    #
+    # Args:
+    #   None
+    # Returns:
+    #   First free server number
+    #
+    snum=$SERVERNUM
+    while [ -f /tmp/.X$snum-lock ]; do
+        snum=$(($snum + 1))
+    done
+    echo $snum
+}
+
+wait_for_x() {
+    # Waits for start of fake X server and exit on timeout
+    #
+    # Args:
+    #   $1: Server number
+    # Returns
+    #   None
+    if [ $# -ne 1 ]; then
+        echo "E: wait_for_x: Missing argument servernum"
+        RC=1
+        exit
+    fi
+    loops=100
+    delay=.1
+    snum=$1
+    while [ ! -e /tmp/.X$snum-lock ]; do
+        sleep $delay
+        loops=$((loops - 1))
+        if [ $loops -le 0 ]; then
+            echo "E: X Server :$snum failed to come up.  Aborting!"
+            RC=1
+            exit
+        fi
+    done
 }
 
 on_exit() {
@@ -93,7 +137,7 @@ while true ; do
             AP_OPT=$2
             shift 2;;
         -s|-screen)
-            SCREEN=$1
+            SCREEN=$2
             shift 2;;
         -X|--xephyr)
             XEPHYR=1
@@ -108,11 +152,16 @@ while true ; do
 done
 
 [ $# -eq 0 ] && usage
-[ $XEPHYR -eq 0 -a ! -x "$XVFB_CMD" ] && echo "E: Xvfb executable not found. Please install xvfb" && RC=1 && exit 1
+if [ $XEPHYR -eq 0 -a ! -x "$XVFB_CMD" ]; then
+    echo "E: Xvfb executable not found. Please install xvfb"
+    RC=1
+    exit 
+fi
 
 TESTLIST="$@"
 echo "I: Running tests $TESTLIST"
 
+SERVERNUM=$(find_free_servernum)
 XCMD="$XVFB_CMD :$SERVERNUM $XVFB_OPT -screen 0 $SCREEN"
 [ $XEPHYR -eq 1 ] && XCMD="$XEPHYR_CMD :$SERVERNUM $XEPHYR_OPT -screen $SCREEN"
 
@@ -122,7 +171,7 @@ X_PID=$!
 export DISPLAY=:${SERVERNUM}.0
 
 export XAUTHORITY=/dev/null
-sleep 1  # Waits from fake X to settle
+wait_for_x $SERVERNUM
 echo "I: Starting autopilot"
 dbus-launch --exit-with-session autopilot run $AP_OPT $TESTLIST
 echo "I: autopilot tests done"
