Make packaging work, re-add accidentally removed .docs file.

diff --git a/debian/rules b/debian/rules
--- a/debian/rules
+++ b/debian/rules
@@ -1,8 +1,17 @@
 #!/usr/bin/make -f
 # -*- makefile -*-
 
+# These commands build the list of supported Python 3 versions
+# The last version should be just “python3” so that the scripts
+# get a correct shebang.
+# Use just “PYTHON3 := $(shell py3versions -r)” if your package
+# doesn’t contain scripts
+PY3REQUESTED := $(shell py3versions -r)
+PY3DEFAULT := $(shell py3versions -d)
+PYTHON3 := $(filter-out $(PY3DEFAULT),$(PY3REQUESTED)) python3
+
 # Uncomment this to turn on verbose mode.
-# export DH_VERBOSE=1
+export DH_VERBOSE=1
 
 %:
 	dh $@ --with python3
@@ -12,14 +21,21 @@ override_dh_auto_clean:
 	rm -rf build
 
 override_dh_auto_build:
+	# Build for each Python 3 version
+	set -ex; for python in $(PYTHON3); do \
+		$$python setup.py build; \
+	done
 	sphinx-build -b html -W  docs/ docs/_build/html/
-	dh_auto_build
 
 override_dh_auto_test:
 ifeq (, $(findstring nocheck, $(DEB_BUILD_OPTIONS)))
 	python3 -m testtools.run discover autopilot.tests.unit
 endif
 
-override_dh_install:
-	dh_install -X.pyc --fail-missing
+override_dh_auto_install:
+	# The same for install; note the --install-layout=deb option
+	set -ex; for python in $(PYTHON3); do \
+		$$python setup.py install --install-layout=deb --root=debian/tmp; \
+	done
+	# dh_install -X.pyc --fail-missing
 
